[build]
builder = "nixpacks"
buildCommand = """
dotnet restore
dotnet publish -c Release -o out
"""

[deploy]
startCommand = "dotnet out/Back_End_WebAPI.dll"
healthcheckPath = "/api/Users/Get"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
watchPattern = "*.cs,*.json"

[env]
ASPNETCORE_ENVIRONMENT = "Production"
DOTNET_RUNNING_IN_CONTAINER = "true"
ASPNETCORE_URLS = "http://0.0.0.0:${PORT}"
PORT = "8080"

[[services]]
name = "postgresql"
plan = "free"

[services.env]
POSTGRES_USER = "postgres"
POSTGRES_PASSWORD = "${RANDOM_STRING}"
POSTGRES_DB = "examdb"
DATABASE_URL = "${DATABASE_URL}"

[[services.ports]]
port = 80
internal_port = 8080

[nixpacks]
start-command = "dotnet out/Back_End_WebAPI.dll"